### ISSUE TITLE
Getting started instructions

### ISSUE THREAD

**Issue by LeonGorbaty1** [manuelsidler/blazor-office-addin#6]
Please add a readme or some text at the front of the repo with steps to test the add-in in Word?

**Comment by manuelsidler** [comment]
I've just added a short instruction (see commit above). Could you verify if it works for you @LeonGorbaty1 ?

**Comment by LeonGorbaty1** [comment]
@manuelsidler it mostly worked THANK YOU !!! I had a few issues, consider adding the following:
* Make sure that the Guid in the manifest matches the Guid in the registry (the sideloading instructions suggest you generate a new guid, so I did, and then added that new one in the manifest <Id></Id> node
* Make sure the registry edit takes - I had to do it twice and reboot once for it to show in Regedit for some reason
* In Office app (Word in my instance) if you get "We can't open this add-in from localhost" then 
a) Make sure your server is running (doh :-))
b) See fix here https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/cannot-open-add-in-from-localhost

I also got a JSException here 
var autoShowAddIn = await JSRuntime.InvokeAsync<bool?>("window.Office.context.document.settings.get", "Office.AutoShowTaskpaneWithDocument");
but that's ok, the add-in is running and I am able to hit breakpoints and debug in VS ... I can work from here...

THANKS AGAIN !!

**Comment by kondzikwawa** [comment]
Hi, I still experience problem with my Add-in. When I run Word I can't see both host and name - only "Not in Office.". It looks there is a problem with connection between Word and Add-in. When I put a break point in this line "await JSRuntime.InvokeVoidAsync("wordWrapper.saveDocumentMetadata", _documentMetadata);" in OnAfterRenderAsync and turn on Add-in in Word the debugging doesn't stop... I would be grateful for any idea or tip. Many thanks in advance.

**Comment by manuelsidler** [comment]
Which .NET Core version are you using?

**Comment by kondzikwawa** [comment]
Many thanks for reply. I'm using .Net Core 3.1
I've tried on two machines and unfortunately the same problem. Do you see anything wrong in attached screenshots and manifest?
![RegEdit](https://user-images.githubusercontent.com/48827797/97088125-1403cf00-162f-11eb-9702-a7a544f97e12.PNG)
![DotNetVersion](https://user-images.githubusercontent.com/48827797/97088133-241bae80-162f-11eb-943c-c6b554a02b05.PNG)
[manifest.txt](https://github.com/manuelsidler/blazor-office-addin/files/5433400/manifest.txt)

**Comment by kondzikwawa** [comment]
Regarding to my previous comment. Any idea what can be wrong with my add-in? 
Thanks in advance for help.

**Comment by manuelsidler** [comment]
Sorry I haven't been able to take a look into your problem. I'll try to find some time this week.

Do you see any errors in the Edge DevTools console? https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10#debug-using-microsoft-edge-devtools

**Comment by kondzikwawa** [comment]
Hi, apologize for delay. I've been extremely busy for last couple of weeks. 
So yes I can see an issue during the Office.Initialize and it breaks the app. If you can take a look and let me know if you have any idea I'd be grateful. Thanks in advance.
<img width="1466" alt="issue" src="https://user-images.githubusercontent.com/48827797/101327680-50059300-386f-11eb-95ab-2c8a548087d2.PNG">

And exception which I can see in Visual Studio:
{"Could not find 'initialize' in 'window.Office'.\nError: Could not find 'initialize' in 'window.Office'.\n    
at https://localhost:44385/_framework/blazor.server.js:8:30944\n    
at Array.forEach (<anonymous>)\n    
at p (https://localhost:44385/_framework/blazor.server.js:8:30904)\n    
at https://localhost:44385/_framework/blazor.server.js:8:31614\n    
at new Promise (<anonymous>)\n    
at e.beginInvokeJSFromDotNet (https://localhost:44385/_framework/blazor.server.js:8:31587)\n    
at https://localhost:44385/_framework/blazor.server.js:1:20052\n    at Array.forEach (<anonymous>)\n    
at e.invokeClientMethod (https://localhost:44385/_framework/blazor.server.js:1:20022)\n    
at e.processIncomingData (https://localhost:44385/_framework/blazor.server.js:1:18006)"}

**Comment by manuelsidler** [comment]
Based on your screenshot, it seems like you try to run the add-in directly in a browser instead of the office application?

Could you try to sideload your add-in in Office based on the official documentation?

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by kondzikwawa** [comment]
Thanks for reply. Yes, in Visual Studio I click IIS Express and then I can see my add-in in browser, but when I open the Word and open my add-in I can see the proper taskpane...however is not working properly, host and platform are blank and buttons are not working. More over if I insert break points in VS, the code doesn't stop if I click e.g. buttons directly from add-in in Word...but when I click any button in browser breakpoints are working normally.
![image](https://user-images.githubusercontent.com/48827797/101337892-87c70780-387c-11eb-9f32-a8fc64f8ccbe.png)

Maybe I do something wrong...

**Comment by manuelsidler** [comment]
With Office add-ins, it's not possible to hit F5 and debug straight away. If you want to debug the client-side code, you have to attach the Edge developer tools to your add-in as described here:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10#debug-using-microsoft-edge-devtools

You can also try to attach Visual Studio directly to your Office add-in as described here:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane

**Comment by kondzikwawa** [comment]
Ok, I get it it's not straightforward but I think there is a problem with Office.js and I have no idea why.
![image](https://user-images.githubusercontent.com/48827797/101348064-56096d00-388b-11eb-8e68-4309becd5fb1.png)
Is not loaded so that's the reason why I can't see the host and platform. 
But of course I've included Office.js in my _Host.cshtml file:
![image](https://user-images.githubusercontent.com/48827797/101348380-d6c86900-388b-11eb-8d7b-84a318608291.png)
And of course I have "Initialize" and "onready" in my code.
![image](https://user-images.githubusercontent.com/48827797/101349174-3a9f6180-388d-11eb-9aa4-4c91201eac92.png)

Many thanks for your help.

**Comment by HansenBerlin** [comment]
> Ok, I get it it's not straightforward but I think there is a problem with Office.js and I have no idea why.
> Is not loaded so that's the reason why I can't see the host and platform.
> But of course I've included Office.js in my _Host.cshtml file:
> And of course I have "Initialize" and "onready" in my code.
> 
> Many thanks for your help.

Did you find a solution? Same problem here...
